### ISSUE TITLE
Feature Request: Add configurable timeout option to get_url download task

### ISSUE THREAD

**Issue by domehahn** [andrewrothstein/ansible-skaffold#3]
Hi 👋,

Thank you for maintaining this role — it's been very useful in automating my development environment setup!

I'd like to request a small but impactful enhancement: adding a configurable timeout parameter to the ansible.builtin.get_url task used to download Skaffold binaries.

Problem
In some environments with slower or unstable network connections, the default get_url timeout (10 seconds) is too short, and results in frequent failures like:

```
fatal: [localhost]: FAILED! => {"msg": "Connection failure: The read operation timed out"}
```

Proposed Solution
Update the download task like so, with a default skaffold_download_timeout variable:

```
yaml
Kopieren
Bearbeiten
- name: Downloading {{ skaffold_url }}
  get_url:
    url: '{{ skaffold_url }}'
    dest: '{{ skaffold_ver_exe }}'
    checksum: '{{ skaffold_checksum }}'
    mode: '0755'
    timeout: '{{ skaffold_download_timeout | default(60) }}'
```
This would allow users to customize the timeout like this in their playbook or inventory:

```
skaffold_download_timeout: 120
```

Benefits
Increased flexibility in various environments

Better resilience for CI/CD pipelines or slower regions

Easy to implement with a non-breaking default

Let me know if this would be acceptable. I’d also be happy to open a PR if you prefer!

Thanks again 🙏
